Adding test for prep-file generation
qiita-spots/qp-knight-lab-processing pull request #43
Opened 2023-03-09 23:01 UTC by charles-cowart

Test against proper testing environment.

2023-03-10 12:06 UTC, antgonza requested changes
Looking good, some minor comments. Do you think is worth checking the contents of the prep info file? Thank you!

2023-03-10 12:06 UTC, antgonza commented on qp_klp/tests/test_klp.py
> +        uploads_fp = ('/home/runner/work/qp-knight-lab-processing/'
you need to take this path from the configuration, right? If not it's gonna fail in other systems.

2023-03-10 17:55 UTC, charles-cowart commented on qp_klp/tests/test_klp.py
> +        # TODO: Fix name
I'll rm. For right now it's fine IMOO.

2023-03-10 17:56 UTC, charles-cowart commented on qp_klp/tests/test_klp.py
> +            print("checking '%s' exists..." % some_path)
ty!

2023-03-10 22:45 UTC, charles-cowart commented
@antgonza It would be good to check the contents of the prep-file results, but I think it would be better to refactor the tests first now that the plugin and the pipeline are mature. Most of the functionality is currently tested in one large test and it requires the full qiita dependency. Some of the functionality and file/directory structures are mocked-up for testing and those mock-ups aren't high-fidelity.

2023-03-11 10:44 UTC, antgonza commented
Thank you @charles-cowart !

2023-03-11 10:44 UTC, antgonza approved these changes

2023-03-11 10:44 UTC, merged