fixes issue encountered during testing.
qiita-spots/qp-knight-lab-processing pull request #96
Opened 2024-12-13 06:36 UTC by charles-cowart

2025-01-09 14:10 UTC, antgonza requested changes
Just one question.

2025-01-09 14:10 UTC, antgonza commented on qp_klp/Protocol.py
> +                        print(join(root, _file), file=f)
I don't really understand this step, it's just used for printing and not nothing gets written in the file, is that what you want to do?

2025-01-09 17:48 UTC, wasade commented on qp_klp/Protocol.py
> +                    if 'corrected.err_barcode_removed' in _file:
Why are these files being examined?

2025-01-09 19:14 UTC, charles-cowart commented on qp_klp/Protocol.py
> +                        print(join(root, _file), file=f)
Actually, this is equivalent to writing f.write("%s\n" % join(root, _file)). There is an additional parameter "file=f" that redirects the print statement from stdout to the file handle 'f'. I've been using this form lately instead of constructing a string just for the sake of appending a newline.

2025-01-09 19:50 UTC, charles-cowart commented on qp_klp/Protocol.py
> +                    if 'corrected.err_barcode_removed' in _file:
yup, I have this marked in my notes. there is a patch for this that expects the integrated results directory instead of Full.

2025-01-10 14:27 UTC, antgonza approved these changes

2025-01-10 14:27 UTC, merged